### ISSUE TITLE
L'utilisateur doit pouvoir choisir quelle valeur il souhaite afficher

### ISSUE THREAD

**Issue by YannisGibert** [IUT-Blagnac/sae-3-01-devapp-Groupe-12#24]
- [x] Ajouter des variables pour stocker le choix des données

- [x] #40

**Comment by Marshall331** [comment]
Il faut choisir les données à afficher dans la variable choixDonnees du fichier .ini. Le fichier donnees.txt comportera donc seulement les choix sélectionnés.
